apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-daemonset
  namespace: kube-system
  labels:
    k8s-app: {{ .Release.Name }}
    app: {{ .Release.Name }}
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
 selector:
   matchLabels:
     name: {{ .Release.Name }}
 template:
   metadata:
     labels:
       name: {{ .Release.Name }}
       app: {{ .Release.Name }}
       version: v1
       kubernetes.io/cluster-service: "true"
   spec:
     serviceAccount: {{ .Release.Name }}-account
     serviceAccountName: {{ .Release.Name }}-account
     tolerations:
     - key: node-role.kubernetes.io/master
       effect: NoSchedule
     containers:
     - name: {{ .Release.Name }}
       image: {{ .Values.image.name }}:{{ .Values.image.tag }}
       imagePullPolicy: {{ .Values.image.pullPolicy }} 
       command: ["fluentd"]
       env:
       - name: FLUENTD_ARGS
         value: --no-supervisor -q
       resources:
         limits:
           memory: 500Mi
         requests:
           cpu: 100m
           memory: 200Mi
       volumeMounts:
       - name: varlog
         mountPath: /var/log
       - name: varlogcontainers
         mountPath: /var/log/containers
       - name: varlibdockercontainers
         mountPath: /var/lib/docker/containers
         readOnly: true
       - name: config-volume
         mountPath: /etc/fluent
     volumes:
     - name: varlog
       hostPath:
         path: /var/log
     - name: varlogcontainers
       hostPath:
         path: /var/log/containers
     - name: varlibdockercontainers
       hostPath:
         path: /var/lib/docker/containers
     - name: config-volume
       configMap:
         name: {{ .Release.Name }}-configmap
     - name: lint-fluent-volume
       emptyDir: {}
     - name: var-logs
       emptyDir: {}
